name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@main

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install arm-none-eabi-gcc arm-none-eabi-g++ nwlink

      - name: Build application
        run: make build

      - name: Upload .bin and .nwa
        id: upload
        uses: actions/upload-artifact@v3
        with:
          name: application
          path: |
            target/NAME.bin
            target/NAME.nwa

      - name: Upload release
        uses: actions/create-release@v3
        with:
          tag_name: ${{ github.event.release.tag_name }}
          release_name: ${{ github.event.release.name }}
          body: |
            Uploaded application: target/NAME.bin
            Uploaded .nwa file: target/NAME.nwa
        if: steps.upload.outputs.artifact_url != ''
